config/routes.rb
Rails.application.routes.draw do
  # Η αρχική σελίδα δείχνει τις αναρτήσεις
  root "posts#index"
resources :posts do
  resources :comments, only: [:create, :destroy]
  collection { get :search }
end
  # Ρυθμίσεις για το Devise (Login/Register) και Google Auth
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }

  # Πλήρεις λειτουργίες για τα Posts (Create, Edit, Delete, View)
 

  # Λειτουργίες για τις Επαφές
  resources :contacts, only: [:index, :create, :destroy]
  
  # Λειτουργίες για το Chat (Μηνύματα)
  resources :messages, only: [:index, :show, :create]

 resources :notifications, only: [:index] do
  member do
    patch :mark_as_read
  end
  collection do
    patch :mark_all_as_read
  end
end
  # Health check για την εφαρμογή
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  # Συνδέουμε το contact_id με τον πίνακα Users
  belongs_to :contact, class_name: 'User', foreign_key: 'contact_id'
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:create] # Για ευκολία στο fetch

  def create
    contact_to_add = User.find_by(id: params[:contact_id])

    if contact_to_add && contact_to_add != current_user && !current_user.friend_users.include?(contact_to_add)
      current_user.friend_users << contact_to_add
      
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path, notice: "Η επαφή προστέθηκε!" }
        format.json { render json: { status: 'success' } }
      end
    else
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.json { render json: { status: 'error' }, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/index.html.erb
<h1>Οι Επαφές μου</h1>

<% if @contacts.present? %>
  <table border="1" style="width: 100%; border-collapse: collapse;">
    <thead>
      <tr style="background: #eee;">
        <th>Username</th>
        <th>Email</th>
        <th>Ενέργειες</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <% user = User.find_by(id: contact.contact_user_id) %>
        <% if user %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to 'Διαγραφή', contact_path(contact), data: { turbo_method: :delete, turbo_confirm: 'Είσαι σίγουρος;' }, style: "color: red;" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Δεν έχετε προσθέσει ακόμα επαφές.</p>
<% end %>

<br>
<%= link_to 'Πίσω στα Posts', posts_path %>